version: '3'

services:
  postgres:
    image: 'pgvector/pgvector:pg16'
    ports:
      - 5432:5432
    restart: always
    shm_size: 128mb
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_DB=airbnb'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    labels:
      - "org.springframework.boot.services-connection=postgres"
      - '5432'
volumes:
  db:
    driver: local