spring:
  application:
    name: spring-ai
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: "ollama"
  ai:
    ollama:
      base-url: http://10.0.0.7:11434
      chat:
        options:
          model: llama3
---
spring:
  config:
    activate:
      on-profile: "mistral"
  ai:
    ollama:
      base-url: http://10.0.0.7:11434
      chat:
        options:
          model: mistral
---
spring:
  config:
    activate:
      on-profile: "openai"
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
