spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
  application:
    name: spring-ai
management:
  endpoints:
    web:
      exposure:
        include: "*"
