spring:
  profiles:
    default: llama3
  application:
    name: spring-ai-airbnb
  ai:
    vectorstore:
      pgvector:
        dimensions: 1536
        index-type: HNSW
        distance-type: COSINE_DISTANCE
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: "llama3"
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3
      embedding.model: llama3
---
spring:
  config:
    activate:
      on-profile: "gpt-4o"
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
etl:
  airbnbLoadListings: false
  clearAirbnbListingsTable: false