spring:
  profiles:
    default: llama3
  application:
    name: spring-ai-airbnb
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 1536
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: "llama3"
  ai:
    ollama:
      base-url: http://10.0.0.7:11434
      chat:
        options:
          model: llama3
---
spring:
  config:
    activate:
      on-profile: "gpt-4o"
  ai:
    openai:
      chat:
        options:
          model: gpt-4o

airbnbLoadListings: false