spring:
  profiles:
    default: llama3
  application:
    name: spring-ai-airbnb
  cloud:
    function:
      definition: csvFileSupplier|csvReader|documentTransformer|vectorStoreConsumer
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DATABASE_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 384
  docker:
    compose:
      file: ./docker-compose.yml
      lifecycle-management: start_and_stop
logging:
  level:
    springframework.web.client: DEBUG
---
spring:
  config:
    activate:
      on-profile: "llama3"
  ai:
    ollama:
      base-url: http://${OLLAMA_HOST}:11434
      chat:
        model: llama3.1:8b
      embedding:
        enabled: true
        model: all-minilm
---
spring:
  config:
    activate:
      on-profile: "gpt-4o"
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
---
spring:
  config:
    activate:
      on-profile: "groq"
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      chat:
        options:
          model: llama3-70b-8192
          temperature: 0.7
      base-url: https://api.groq.com/openai