package com.byteworksinc.airbnb.dao.impl;

import com.byteworksinc.airbnb.entities.Listing;

public class ListingObjectBuilder {

    public static Object[] build(Listing listing) {

        return new Object[]{
                listing.id(),
                listing.listingUrl(),
                listing.scrapeId(),
                listing.source(),
                listing.lastScraped(),
                listing.name(),
                listing.description(),
                listing.neighborhoodOverview(),
                listing.pictureUrl(),
                listing.hostId(),
                listing.hostUrl(),
                listing.hostName(),
                listing.hostSince(),
                listing.hostLocation(),
                listing.hostAbout(),
                listing.hostResponseTime(),
                listing.hostResponseRate(),
                listing.hostAcceptanceRate(),
                listing.hostIsSuperhost(),
                listing.hostThumbnailUrl(),
                listing.hostPictureUrl(),
                listing.hostNeighbourhood(),
                listing.hostListingsCount(),
                listing.hostTotalListingsCount(),
                listing.hostVerifications(),
                listing.hostHasProfilePic(),
                listing.hostIdentityVerified(),
                listing.neighbourhood(),
                listing.neighbourhoodCleansed(),
                listing.neighbourhoodGroupCleansed(),
                listing.latitude(),
                listing.longitude(),
                listing.propertyType(),
                listing.roomType(),
                listing.accommodates(),
                listing.bathrooms(),
                listing.bathroomsText(),
                listing.bedrooms(),
                listing.beds(),
                listing.price(),
                listing.minimumNights(),
                listing.minimumMinimumNights(),
                listing.maximumNights(),
                listing.maximumMinimumNights(),
                listing.maximumMaximumNights(),
                listing.minimumMaximumNights(),
                listing.minimumNightsAvgNtm(),
                listing.calendarUpdated(),
                listing.hasAvailability(),
                listing.availability30(),
                listing.availability60(),
                listing.availability90(),
                listing.availability365(),
                listing.calendarLastScraped(),
                listing.numberOfReviews(),
                listing.numberOfReviewsLtm(),
                listing.numberOfReviewsL30d(),
                listing.firstReview(),
                listing.lastReview(),
                listing.reviewScoresRating(),
                listing.reviewScoresAccuracy(),
                listing.reviewScoresCleanliness(),
                listing.reviewScoresCheckin(),
                listing.reviewScoresCommunication(),
                listing.reviewScoresLocation(),
                listing.reviewScoresValue(),
                listing.license(),
                listing.instantBookable(),
                listing.calculatedHostListingsCount(),
                listing.calculatedHostListingsCountEntireHomes(),
                listing.calculatedHostListingsCountPrivateRooms(),
                listing.calculatedHostListingsCountSharedRooms(),
                listing.reviewsPerMonth()
        };
    }
}
